### ISSUE TITLE
Handling rel="sponsored" & rel="ugc" (nofollow)

### ISSUE THREAD

**Issue by xherriot** [stevenvachon/robot-directives#2]
Hello,

As describe [here](https://support.google.com/webmasters/answer/96569?hl=en), Google recommend "sponsored" & "ugc" values instead of "nofollow" for advertisements & user-generated content links.

Is there a way to handle these values with robot-directives ?

Thank you.

**Comment by stevenvachon** [comment]
It currently does not support those.

**Comment by stevenvachon** [comment]
I think what you're looking for is [link-types](https://npmjs.com/link-types). Moved this to that project's repo.
